### ISSUE TITLE
mvn could not resolve java-crypto-conditions dependencies

### ISSUE THREAD

**Issue by diminator** [authenteq/java-bigchaindb-driver#1]
upon `mvn install`
```
[WARNING] The POM for org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.227 s
[INFO] Finished at: 2017-09-12T17:40:09+02:00
[INFO] Final Memory: 10M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project java-bigchaindb-driver: Could not resolve dependencies for project com.authenteq:java-bigchaindb-driver:jar:0.1: Could not find artifact org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT -> [Help 1]
```

`mvn -v`
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.0-59-generic", arch: "amd64", family: "unix"
```

**Comment by bodia** [comment]
java-crypto-conditions dependency should be installed into the local maven repo before building. Updated the installation guide accordingly.

**Comment by diminator** [comment]
FYI: https://github.com/interledger/java-crypto-conditions/issues/70

which yields a different version: `java-crypto-conditions:0.3.0.SNAPSHOT` rather than `2.0.0.SNAPSHOT`
Wondering which one is used in the project?

**Comment by bodia** [comment]
The one used in this driver is 2.0.0.SNAPSHOT, and this rises the question: maybe it would be just easier to maintain and build if the static version will be included with the driver? In such case both Android and standard Java runtime will be supported out of the box.

**Comment by alvin-reyes** [comment]
Did you resolved this? Workround is to include it (if you're still using Maven) like this:

```
<dependency>
    <groupId>org.interledger</groupId>
    <artifactId>java-crypto-conditions</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/libs/java-crypto-conditions-2.0.0-SNAPSHOT.jar</systemPath>
</dependency>
```

**Comment by bodia** [comment]
Right now we would probaly stick with including the static dependency. Later we should change the driver to support 3.0.0 of java-crypto-conditions

**Comment by agwego** [comment]
I don't know where you got java-crypto-conditions-2.0.0-SNAPSHOT.jar from but it doesn't match any of the various crypto-conditions jars available or source for that matter.

From java-crypto-conditions-2.0.0-SNAPSHOT.jar 
`
org/interledger/cryptoconditions/types/Ed25519Sha256Condition.class
org/interledger/cryptoconditions/types/ThresholdSha256Fulfillment.class
org/interledger/cryptoconditions/types/Ed25519Sha256Fulfillment.class
`

So https://github.com/interledger/java-crypto-conditions is now DEPRECATED in favour of https://github.com/hyperledger/quilt/tree/master/crypto-conditions.
Both versions use the following class structure.
`
./org/interledger/cryptoconditions/Ed25519Sha256Condition.java
./org/interledger/cryptoconditions/Ed25519Sha256Fulfillment.java
./org/interledger/cryptoconditions/ThresholdSha256Fulfillment.java
`

Unless I'm totally missing something like the wrong github project,java-crypto-conditions-2.0.0-SNAPSHOT.jar seems out of sync with those projects.

**Comment by bodia** [comment]
Yeah, right, the driver right now depends on a deprecated version, and updating it to proper version is in TODO list.

**Comment by agwego** [comment]
I took a quick shot at doing it, the stumbling block is uri which is missing from the quilt version. Which poses a quandary which is fork quilt and submit the pull request or update java-bigchaindb-driver and remove the uri references.

**Comment by alvin-reyes** [comment]
I'll create an issue here for Tracking purposes. I think we need to use the latest version and avoid using the deprecated one.

**Comment by alvin-reyes** [comment]
Newly Travis CI build failed because of this. Issue for this is here https://github.com/authenteq/java-bigchaindb-driver/issues/43

**Comment by alvin-reyes** [comment]
This is already fixed by https://github.com/authenteq/java-bigchaindb-driver/pull/58
