### ISSUE TITLE
Wrapper for Creating new Account (KeyPair)

### ISSUE THREAD

**Issue by alvin-reyes** [authenteq/java-bigchaindb-driver#13]
We need a standard API for creating and converting new KeyPair accounts. This way, we can reuse the keys for identification and asset transfers.

**Comment by bodia** [comment]
I have some code for this that I can share.

**Comment by alvin-reyes** [comment]
Do you have PR for it?

**Comment by bodia** [comment]
@alvin-reyes I'll create one in the nearest time

**Comment by bodia** [comment]
See https://github.com/authenteq/java-bigchaindb-driver/pull/23

**Comment by alvin-reyes** [comment]
Thanks @bodia
