### ISSUE TITLE
WebSocket Event Stream API

### ISSUE THREAD

**Issue by alvin-reyes** [authenteq/java-bigchaindb-driver#14]
Support for WebSocket Events Stream

**Comment by alvin-reyes** [comment]
I have a simple implementation for this but I'm still thinking if its better to have a separate project for this. @bodia , @tzclucian . Thoughts?

**Comment by tzclucian** [comment]
I would go with this project/repo.

I'm thinking that in the future they will share certain POJOs and it will be easier.
- it won't require another repo and artifact for the models

**Comment by alvin-reyes** [comment]
Got it. I already have this on my branch. I'll raise PR for it.

**Comment by alvin-reyes** [comment]
https://github.com/authenteq/java-bigchaindb-driver/pull/34

**Comment by alvin-reyes** [comment]
This can now be closed.
