### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by alvin-reyes** [authenteq/java-bigchaindb-driver#24]
Do you guys think it's good if we create a Java 8 build?
@bodia , @tzclucian

**Comment by tzclucian** [comment]
Can't really come up with an example from the code right now, but keeping up with the latest Java versions sounds good to me.

It is something we should aim to achieve.

We could even push for a Java 9 build 😃

**Comment by agwego** [comment]
I'm building with JDK 1.8_144 without issue.

**Comment by alvin-reyes** [comment]
I'm also using JDK 1.8. Do we want to push for JDK 8 for now?

**Comment by bodia** [comment]
Yeah, creating java 8 build is a good idea.

**Comment by alvin-reyes** [comment]
https://github.com/authenteq/java-bigchaindb-driver/pull/34

**Comment by alvin-reyes** [comment]
This can now be closed.
