### ISSUE TITLE
WARNING: A connection to ... was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by yrozhkov** [authenteq/java-bigchaindb-driver#27]
okhttp3 throws this warning.
I have a number of transactions I am trying to send.
After a while sending transactions starts to fail I see on bigchaindb side messages like 
[CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:1509) (webapi     - pid: 181)
I keep retrying and after a minute or so I get okhttp3 warning When transactions start flowing again

**Comment by alvin-reyes** [comment]
Will look into it. It seems that the one of the HttpCalls was not closed properly.

**Comment by bodia** [comment]
Maybe we should set smaller socket timeout

**Comment by yrozhkov** [comment]
It is also happens after I send ~ 4000 transactions
gunicorn says they recycle their transactions if they are not used. So the chain of events
1. Send 4000 transactions
2. Transactions stop flowing with okhttp throwing exception Bad file descriptor (Write failed)
3. I see   okhttp3.internal.platform.Platform log
WARNING: A connection to .. was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

4. after 1 minute or so connections will flow again

**Comment by bodia** [comment]
Fixed with https://github.com/authenteq/java-bigchaindb-driver/commit/d69ddd7e0218ea16f67e9e3367d2f967846ddbc9

**Comment by alvin-reyes** [comment]
Please close this one if it's already verified.

**Comment by bodia** [comment]
I haven't really tested it, just if someone confirms.

**Comment by alvin-reyes** [comment]
Verified this on my testing. It can now be closed.
