### ISSUE TITLE
Why was the Maven setup removed?

### ISSUE THREAD

**Issue by alvin-reyes** [authenteq/java-bigchaindb-driver#3]

**Comment by tzclucian** [comment]
Following.

**Comment by bodia** [comment]
The original idea is that gradle-only system would be much easier to maintain, but if there is such a strong demand for mvn setup, then I see no obstacles why it shouldn't be added.

**Comment by alvin-reyes** [comment]
Ok, with your permission, can I fork this and create the maven changes? I'll be adding the code to handle the other API endpoints as well. 

We're planning to use BigChainDB for our Enterprise project. It would be awesome to collaborate.

Thanks

**Comment by bodia** [comment]
Sure, sounds good. Just create the pull requests and I'll include the changes.

**Comment by tzclucian** [comment]
@alvin-reyes 
Awesome to hear that. I'll jump in and help where possible as I'm in the same situation.

**Comment by alvin-reyes** [comment]
Added the pom.xml and a manual dependency for the crypto-conditions jar file.

https://github.com/alvin-reyes/java-bigchaindb-driver

**Comment by tzclucian** [comment]
Looking forward for the pull request.

I'm like what I'm seeing the the forked repo right now

**Comment by bodia** [comment]
I agree, looks good, the only thing that is the setup with the global config makes it impossible to have multiple connection instances (I can't think about the usecase for this yet, but maybe useful for someone).

**Comment by tzclucian** [comment]
Yep, also the `system` scoped dependency can prove to be a hassle.

**Comment by alvin-reyes** [comment]
@tzclucian, we can use extend the maven install plugin to include that without using a system scoped attribute. I'll modify the pom.xml for that.

@bodia , you are right. I'll modify the code so that we can easily create multiple instances of DB connection and make sure those can be "injected" easily when accessing the APIs. 

Thank you for the feedback. Once it's done, I'll send the PR for your review.

**Comment by alvin-reyes** [comment]
Hi @tzclucian , @bodia, is there a specific reason why didn't we use jackson or gson/guava for JSON parsing? I'd like to know if you're open to migrating it to use these libraries as oppose to using the org.json library

**Comment by bodia** [comment]
@alvin-reyes actually migrating to something other than org.json has been one of the most important improvements for the driver that I considered. No objections at all. Moreover, getting rid of org.json will make the driver compatible with Android.

**Comment by tzclucian** [comment]
> Hi @tzclucian , @bodia, is there a specific reason why didn't we use jackson or gson/guava for JSON parsing? I'd like to know if you're open to migrating it to use these libraries as oppose to using the org.json library

I do agree with jackson. I was even thinking about introducing POJOs/models for the actual request and response entities.

**Comment by alvin-reyes** [comment]
Yes. Got this working now on my local branch. Introduce a bunch of POJOs. I haven't finish them yet but please feel free to check it out. https://github.com/alvin-reyes/java-bigchaindb-driver

**Comment by alvin-reyes** [comment]
PR for this: https://github.com/authenteq/java-bigchaindb-driver/pull/10

Remaining items: Support for Multiple Connections.

**Comment by tzclucian** [comment]
I think we can close this issue now?

What do you think @alvin-reyes , @bodia ?

**Comment by alvin-reyes** [comment]
Yes. I think so. I'll create a separate issue for the features that I think is beneficial for the library.

**Comment by dominic-healid** [comment]
Hello Guys, I'm new with Java and Maven, how can use install this on my java project? I know it's says mvn clean install, but what should I do first before running that command? Guide me please.

**Comment by tzclucian** [comment]
> Hello Guys, I'm new with Java and Maven, how can I install this on my java project? I know it's says mvn clean install, but what should I do first before running that command? Guide me please.

Hey @dominic-healid ,
Best thing you could do is to start off with a Maven tutorial.
Check https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html .

**Comment by dominic-healid** [comment]
Thanks, I resolved it somehow I'm not sure if this is really the way to add this library, but what I actually did, I downloaded this project, and run maven and then I added this whole project to my project. 

But yeah, will definitely look at that tutorial.

Thank you @tzclucian
