### ISSUE TITLE
Status should be an enum and enumerate the possible values

### ISSUE THREAD

**Issue by agwego** [authenteq/java-bigchaindb-driver#35]
com.authenteq.model.Status should be an enum and not a pojo.
Status should also enumerate all possible values.

**Comment by alvin-reyes** [comment]
Agree. Need to make it ENUM and create an ENUM serializer.

**Comment by agwego** [comment]
I can take this on, I have a fair amount of experience with gson.

**Comment by alvin-reyes** [comment]
Sure. As a reference, you can do it this way:

```
public class EnumLowercaseSerializer implements JsonSerializer<Enum<?>> {
	public JsonElement serialize(Enum<?> src, Type typeOfSrc,
			JsonSerializationContext context) {
		return context.serialize(src.name().toLowerCase());
	}
}
```

and on the Gson builder

```
GsonBuilder builder = new GsonBuilder();

			// Serializes enums as lower-case.
			builder.registerTypeHierarchyAdapter(Enum.class,
					new EnumLowercaseSerializer());
```

**Comment by agwego** [comment]
I have a working solution for this. I guess the next one is block status.

**Comment by alvin-reyes** [comment]
Great. You can just merge them into a single PR.
