### ISSUE TITLE
Logging - Would it be better to use SLF4J as the logging wrapper

### ISSUE THREAD

**Issue by agwego** [authenteq/java-bigchaindb-driver#39]
Nicer API than java.util.logging.Logger more flexibility for users of java-bigchaindb-driver

**Comment by alvin-reyes** [comment]
Sure but I'd like to lower the priority on this one and focus more on the crucial ones like #36, #35, #37

**Comment by agwego** [comment]
Of course

**Comment by alvin-reyes** [comment]
Want to take this on @agwego? I'll assign it to you if you want. Let me know if otherwise, I can take a look at it as well.
