### ISSUE TITLE
CI Build failure due to missing crypto-condition dependencies

### ISSUE THREAD

**Issue by alvin-reyes** [authenteq/java-bigchaindb-driver#43]
Travis CI is failing due to this missing dependency. Need to use the latest and greatest crypto condition library 

`[ERROR] Failed to execute goal on project java-bigchaindb-driver: Could not resolve dependencies for project com.authenteq:java-bigchaindb-driver:jar:0.0.1-SNAPSHOT: Could not find artifact org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) `

https://travis-ci.org/authenteq/java-bigchaindb-driver

**Comment by adonnini** [comment]
This could be helpful

https://github.com/hyperledger/quilt/issues/14

**Comment by agwego** [comment]
I've fixed this in the latest pull request look at the .travis.yml

**Comment by alvin-reyes** [comment]
This is already fixed by https://github.com/authenteq/java-bigchaindb-driver/pull/58
