### ISSUE TITLE
AssetsApi.getAssets returns assets but no IDs

### ISSUE THREAD

**Issue by akarion-s** [authenteq/java-bigchaindb-driver#44]
hey guys,

we are about to use the java-bigchaindb-driver in our production system.

i think i just found that the asset API returns the requested asset-data as intended, but not the corresponding tx-ids. the regular REST API does return the tx-ids. is that a bug maybe?

thanks in advance!

cheers,
sascha

**Comment by alvin-reyes** [comment]
We will check and update this thread.

**Comment by alvin-reyes** [comment]
@akarion-s , fix for this is now merged in master (PR #46). Please verify and close.
