### ISSUE TITLE
 	java-crypto-conditions-2.0.0-SNAPSHOT.jar source

### ISSUE THREAD

**Issue by adonnini** [authenteq/java-bigchaindb-driver#68]
Hi,

Where could I get the source for  	java-crypto-conditions-2.0.0-SNAPSHOT.jar

Thanks,

Alex Donnini

**Comment by agwego** [comment]
You can find it here, [https://github.com/bodia/java-crypto-conditions](https://github.com/bodia/java-crypto-conditions) not sure of the current state. But the goal is move to the official crypto conditions here: [https://github.com/hyperledger/quilt/tree/master/crypto-conditions](https://github.com/hyperledger/quilt/tree/master/crypto-conditions)

**Comment by adonnini** [comment]
Great. Thanks!

I took a quick look at the crypto-conditions sources on the hyperledger site.

They are pretty different from the ones in the 2.0.0-snapshot. It sounds like it's not going to be a simple move. Am I wrong?

Thanks,

Alex Donnini

**Comment by agwego** [comment]
I don't think you're wrong, it will require some serious effort, which is probably why it hasn't happened yet.
